sets.exported={
    main={ name="Heishi Shorinken", augments={'Path: A',}},
    sub="Gleti's Knife",
    ammo="Sapience Orb",
    head={ name="Fighter's Mask", augments={'Mag. Acc.+6','"Fast Cast"+4','STR+4','"Mag.Atk.Bns."+1',}},
    body={ name="Fighter's Lorica", augments={'"Fast Cast"+5',}},
    hands={ name="Fighter's Mufflers", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs="Fighter's Cuisses",
    feet={ name="Fighter's Calliga", augments={'CHR+7','Pet: MND+3','Quadruple Attack +3','Accuracy+15 Attack+15','Mag. Acc.+14 "Mag.Atk.Bns."+14',}},
    neck="Baetyl Pendant",
    waist="Flume Belt +1",
    left_ear="Etiolation Earring",
    right_ear="Loquac. Earring",
    left_ring="Kishar Ring",
    right_ring="Rahab Ring",
    back="Solemnity Cape",
}